[#INTERNAL-501] Update to langchain to 0.3.1 on…
…chatbot.ex

Langchain.ex has progressed to 0.3.1. We should update to that. However,
it introduces a breaking change:

    Compiling 10 files (.ex)
        error: module LangChain.Utils.ApiOverride is not loaded and could not be found
        │
     12 │   import LangChain.Utils.ApiOverride
        │   ^
        │
        └─ lib/chatbot/llm_mock.ex:12:3: Chatbot.LLMMock (module)

The background is
[this PR](https://github.com/brainlid/langchain/pull/155):

> This change includes the Mimic testing library for mocking out live
> calls and forcing a specific return value.
>
> Originally, was using `LangChain.Utils.ApiOverride` which provided
> process-level result overrides. However, it had the negative
> requirement of requiring testing-aware to be in the production code,
> specifically in the ChatXYZ.call functions.
>
> Using Mimic removes that requirement, keeping the production level
> code cleaner.

The reasoning is sound, however, it crashes with what we do in
`Chatbot.LLMMock`. As LLM Mock is not used in tests (and `LLMMock` does
not have tests itself), I would take it out for now.&#x20;

https://bitcrowd.atlassian.net/browse/INTERNAL-501